#!/bin/sh
#
# Copyright 2017 PostgreSQL Global Development Group
#

PSQL="psql -v ON_ERROR_STOP=1 -X"

$PSQL <<- __EOF__
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS time;
__EOF__
RC=$?
if [ $RC -ne 0 ]; then
	echo "ERROR: creating tables $RC"
	exit 1
fi

exit 0
