#!/bin/sh
#
# Copyright 2017 PostgreSQL Global Development Group
#

trap 'cleanup' EXIT

cleanup() {
	if [ $? -ne 0 ]; then
		tsdss-pgsql-stop
	fi
}

usage() {
	echo "Usage: `basename $0` <options>"
	echo
	echo "Options:"
	echo "  -g         Flag to generate datafiles for table partitioning"
	echo "  -h         This help message"
	echo "  -i <path>  Path to data files"
	echo "  -o <path>  Path to save results"
	echo "  -P <str>   Database parameters"
	echo "  -y <int>   Years of data expected to be generated"
}

FLAG_CHUNKS=""
FLAG_DATAFILE_PATH=""
FLAG_DBPARAMS=""
FLAG_GENERATE_DATA=""
FLAG_YEARS=""
OUTDIR="."
while getopts "ghi:o:P:y:" OPT; do
	case $OPT in
	g)
		FLAG_GENERATE_DATA="-g"
		;;
	h)
		usage
		exit 0
		;;
	i)
		FLAG_DATAFILE_PATH="-i $OPTARG"
		;;
	o)
		OUTDIR=$OPTARG
		;;
	P)
		FLAG_DBPARAMS="-P \"$OPTARG\""
		;;
	y)
		FLAG_YEARS="-y $OPTARG"
		;;
	esac
done

FLAG_OUTDIR="-o $OUTDIR"

if [ -z $PGDATA ]; then
    echo "ERROR: PGDATA not defined."
    exit 1
fi

if [ -z $PGDATABASE ]; then
    echo "ERROR: PGDATABASE environment variable not defined"
    exit 1
fi

if [ -d $PGDATA ]; then
	echo "  PGDATA directory '$PGDATA' already exists, skipping initdb..."
else
	echo "  Initializing PostgreSQL database instance..."
	initdb -A trust -D $PGDATA --locale=C || exit 1
fi

eval tsdss-pgsql-start $FLAG_DBPARAMS $FLAG_OUTDIR || exit 1
dropdb --if-exists $PGDATABASE || exit 1
createdb $PGDATABASE || exit 1
tsdss-pgsql-create-tables $FLAG_DATAFILE_PATH $FLAG_GENERATE_DATA \
		$FLAG_YEARS || exit 1
tsdss-pgsql-stop || exit 1

exit 0
